version: 2.1

orbs:
  docker: circleci/docker@1.2.0
  gcp-cli: circleci/gcp-cli@3.1.0

jobs:
  build:
    docker:
      - image: circleci/python:3.9

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt

      # Add more steps here as needed for your specific build process

  test:
    docker:
      - image: circleci/python:3.9

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Install test dependencies
          command: pip install pytest
      - run:
          name: Run tests
          command: pytest

  deploy:
    docker:
      - image: circleci/python:3.9

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt

      # Add steps for deploying your application (e.g., pushing to a registry, deploying to a cloud platform, etc.)

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test