version: 2.1

orbs:
  docker: circleci/docker@1.2.0
  gcp-cli: circleci/gcp-cli@3.1.0
  win: circleci/windows@5.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run: systeminfo
      - run:
          name: "Check Docker"
          shell: powershell.exe
          command: |
            docker info
            docker run -it mcr.microsoft.com/windows/nanoserver:ltsc2022 cmd.exe
      - run: pip install -r requirements.txt
      - run: docker build -t mydock_image .

      # Add more steps here as needed for your specific build process

workflows:
  version: 2
  build_only:
    jobs:
      - build